steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/medical-chatbot', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/medical-chatbot']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'medical-chatbot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/medical-chatbot'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'DB_USER=${_DB_USER}'
      - '--set-env-vars'
      - 'DB_PASS=${_DB_PASS}'
      - '--set-env-vars'
      - 'DB_NAME=${_DB_NAME}'

images:
  - 'gcr.io/$PROJECT_ID/medical-chatbot'