version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile1  # Dockerfile pour FastAPI
    ports:
      - "5000:5000"
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - REGION=${REGION}
      - INSTANCE=${INSTANCE}
      - DATABASE=${DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./data:/app/data  # Montage du dossier data pour le fichier CSV
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile2  # Dockerfile pour Streamlit
    ports:
      - "8080:8080"
    environment:
      - API_HOST=http://backend:5000  # L'API FastAPI est accessible via le nom du service "backend"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge